# Change these first
owner: labgover # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: '[VM] Agnus Dei'
    check: "tcp-ping"
    url: 75.119.128.234
    port: 443
  - name: "SICGESP Legado"
    url: https://sicgesp.com.br/login/
  - name: "SICGESP Novo"
    url: https://prod.sicgesp.com.br/
  - name: "SEGOV Legado"
    url: https://segov.com.br/
  - name: "DePara Legado"
    url: https://appdepara.com.br/
  - name: "DePara Teste"
    url: https://depara.segov.com.br/
  - name: "GovStore"
    url: https://govstore.com.br/
  - name: "Website Laboratório"
    url: https://labgover.com.br
  - name: "RECASP Legado"
    url: https://recasp.com.br/login/
  - name: "RECASP Prod"
    url: https://recasp.segov.com.br/
  - name: "RECASP Prod Admin"
    url: https://recasp-admin.segov.com.br/
  - name: "RECASP Dev"
    url: https://dev-recasp.segov.com.br/
  - name: "Controle Social"
    url: https://controlesocial.net.br/login/
  - name: "TranspGov Penedo"
    url: https://penedo-al-transp.segov.com.br/
  - name: "Google Sites"
    url: https://sites.google.com/
  - name: "Google Spreadsheets"
    url: https://docs.google.com/spreadsheets
  - name: "Muniware"
    url: http://numiware.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.labgover.com.br
  #baseUrl: /monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor do LabGover
  introTitle: "**LabGover** é o Laboratório de Inovação em Governança, da Gestão de Riscos, do Controle e da Auditoria."
  introMessage: "O monitor do Labgover monitora os serviços da Sala de Gestão e Governança e de sua equipe de implementação."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://labgover.com.br/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
