# Change these first
owner: pazkero # Your GitHub organization or username, where this repository lives
repo: pilabunb # The name of this repository

sites:
  - name: '[VM] Agnus Dei'
    check: "tcp-ping"
    url: 75.119.128.234
    port: 443
  - name: "Website Sala SEB"
    url: https://www.projetosalasebunb.com.br/adesao
  - name: "SICGESP"
    url: https://sicgesp.com.br/login/
  - name: "SEGOV"
    url: https://segov.com.br/
  - name: "DePara"
    url: https://appdepara.com.br/
  - name: "GovStore"
    url: https://govstore.com.br/
  - name: "Website Laboratório (antigo)"
    url: https://www.pilab.net.br
  - name: "RECASP"
    url: https://recasp.com.br/login/
  - name: "Controle Social"
    url: https://controlesocial.net.br/login/
  - name: "Google Sites"
    url: https://sites.google.com/
  - name: "Polichat"
    url: https://app-spa.poli.digital/
  - name: "Google Spreadsheets"
    url: https://docs.google.com/spreadsheets
  - name: "Muniware"
    url: http://numiware.com/
  - name: "Zapier"
    url: https://zapier.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /pilabunb
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor do LabGover
  introTitle: "**LabGover** é o Laboratório de Inovação em Governança, da Gestão de Riscos, do Controle e da Auditoria."
  introMessage: "O monitor do Labgover monitora os serviços da Sala de Gestão e Governança e de sua equipe de implementação."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.projetosalasebunb.com.br/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
